#pragma once
#include "CoreMinimal.h"
#include "EInputEventNames.generated.h"

UENUM(BlueprintType)
enum class EInputEventNames : uint8 {
    None,
    DropItem_Y,
    Confirm_A,
    Cancel_B,
    CloseAll,
    InspectItem_X,
    SwitchMenuTabLeft,
    SwitchMenuTabRight,
    OpenStatisticsPanel,
    MapZoom,
    MapPan,
    ScrollUp,
    ScrollDown,
    MouseLeft,
    MouseRight,
    NavigateUp,
    NavigateSideways,
    UseConsumable,
    DragEvent,
    Confirm_InGame,
    TimedOut,
    JumpClimb,
    UseLadder,
    Sprint,
    DodgeDash,
    DodgeDashKeyboard,
    ResetCamera,
    LockOn,
    NextTarget,
    NextTargetL,
    NextTargetR,
    LightAttack,
    HeavyAttack,
    Guard,
    SecondaryAttack,
    CycleWeapon,
    CycleOffHandItem,
    SwitchConsumable,
    PreviousConsumable,
    Inventory,
    PlayerMenu,
    EmoteMenu,
    DropLantern,
    DisplayOptions,
    Walk,
    MoveRight,
    MoveForward,
    Turn,
    Lookup,
    CameraTurnRate,
    CameraLookUpRate,
    TargetSwitch,
    NonRebindableNonIcon,
    _Max,
};

