#pragma once
#include "CoreMinimal.h"
#include "EPostProcessEffect.generated.h"

UENUM(BlueprintType)
enum class EPostProcessEffect : uint8 {
    Unassigned,
    Damage,
    Death,
    SaveStoneUse,
    ChargedAttack,
    HealingItemUse1,
    HealingItemUse2,
    HealingItemUse3,
    StaminaItemUse1,
    StaminaItemUse2,
    StaminaItemUse3,
    WraithTravel,
    ProgressionMilestone,
    MatriarchAoe1,
    MatriarchAoe2,
    MatriarchAoe3,
    SaveStoneApproach,
    PotionDwale,
    PotionPanacea,
    PotionNectar,
    PotionTonic,
    PotionLeechdraught,
    PotionSturm,
    ConsumableBeanGrubs,
    ConsumableLingonberries,
    ConsumableWhiteSapote,
    ConsumableFireKelp,
    ConsumableAppleCricket,
    ConsumableMushroom,
    ConsumableFlesh,
    SaveStoneProximityActivation,
    DrinkSap,
    ConsumableStatIncrease,
    ConsumableStatDecrease,
    PostProcess01,
    PostProcess02,
    PostProcess03,
    PostProcess04,
    PostProcess05,
    PostProcess06,
    PostProcess07,
    PostProcess08,
    BossDefeated,
    AshChipsRegained,
    NpcAccquired,
};

