#pragma once
#include "CoreMinimal.h"
#include "ETalismanType.generated.h"

UENUM(BlueprintType)
enum class ETalismanType : uint8 {
    None,
    Invalid,
    Wanderer,
    Shadowfiend,
    GefnsBlessing,
    Wake,
    Fuse,
    Sentinel,
    Riak,
    ColdBlood,
    Stalker,
    Grit,
    Veiled,
    Traveler,
    Forager,
    Scavenge,
    DoubleShot,
    LastStand,
    Windrunner,
    Recluse,
    Bloodthirsty,
    AxungHominis,
    Placebo,
    Industrious,
    SureFooted,
    Fierce,
    Amity,
    Rekindle,
    Protector,
    AttackStaminaReduction,
    LesserHealth,
    LesserStamina,
    GreaterHealth,
    GreaterStamina,
    HealthRegen,
    LowHealthTank,
    LowStaminaDamage,
    BlockCostReduction,
    StaminaRegen,
    Tank,
};

