#pragma once
#include "CoreMinimal.h"
#include "ETravelPointName.generated.h"

UENUM(BlueprintType)
enum class ETravelPointName : uint8 {
    None,
    Town,
    Foothills,
    Foothills_Ashsmith1,
    Foothills_Ashsmith2,
    Foothills_Ashsmith3,
    LightAnnex,
    LightAnnex_Arena,
    Badlands_Gateway,
    Badlands_PilgrimsPass,
    Badlands_Sanctum,
    Badlands_InnerSanctum,
    Badlands_RachisCave,
    Fjord_Plains,
    Fjord_Coastline,
    Fjord_Hillside,
    Fjord_ListenerTemple,
    FjordDiasoraPuzzle,
    Fjord_RachisCave,
    ListenerTemple_Entrance,
    ListenerTemple_Door,
    ListenerTemple_Walkway,
    ListenerTemple_Hallway,
    ListenerTemple_Matriarch,
    SunkenCoastline_BrokenPath,
    SunkenCoastline_Canyon_TS,
    SunkenCoastline_Canyon,
    SunkenCoastline_RachisCave,
    Highlands_Boglands,
    Highlands_Forest,
    Highlands_Hills,
    Highlands_ListenerOutpost,
    Highlands_Overpass,
    Highlands_Underpass,
    Highlands_Gefn,
    Highlands_RachisCave1,
    Highlands_RachisCave2,
    Badlands_Lathyrus,
    Lathyrus_Dungeon,
    Lathyrus_ShadowOfGod,
    Gnaw,
    Gnaw_InnerSanctum,
    Sissna_Cave,
    Sissna_Arena,
    DLC_WildmanBoat_Fjord,
    DLC_WildmanBoat_RiakIsland,
    DLC_RiakIsland_1,
    DLC_RiakIsland_2,
    DLC_RiakIsland_3,
};

