#pragma once
#include "CoreMinimal.h"
#include "ETrackedPlayerState.generated.h"

UENUM(BlueprintType)
enum class ETrackedPlayerState : uint8 {
    None,
    InCombat,
    HasCloseHostileCreature,
    IsLockedOn,
    UnderDefinedHealthValue,
    IsHoldingUpShield,
    IsLocalPlayerDowned,
    IsAimingSpear,
    IsMoving,
    IsSprinting,
    IsReadyNeutral,
    InDarkness,
    InTown,
    InTutorialArea,
    HasLantern,
    HasLanternEquiped,
    HasDrawnLantern,
    Has1H,
    Has1HEquiped,
    HasDrawn1H,
    Has2H,
    Has2HEquiped,
    HasDrawn2H,
    HasSpear,
    HasSpearEquiped,
    HasDrawnSpear,
    HasShield,
    HasShieldEquiped,
    HasDrawnShield,
    HasPotion,
    HasPotionEquiped,
    HasConsumable,
    HasConsumableEquiped,
    HasWaterBottle,
    HasWaterBottleEquiped,
    HasArmour,
    HasArmourEquiped,
    HasMoney,
    HasActiveQuest,
    HasCompanion,
    Max,
};

